In [2]:
import torch
torch.__version__

'1.3.0'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#Dimension is number of square brackets

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8,8],
                       [9,10,9]])
MATRIX

tensor([[ 7,  8,  8],
        [ 9, 10,  9]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
ONES = torch.ones([2,2,2])

In [15]:
ONES

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [16]:
ONES = torch.ones([2,2,2,2])

In [17]:
ONES

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [18]:
# RAND tensors
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.7357, 0.0386, 0.7119, 0.9553],
        [0.1438, 0.7315, 0.4101, 0.3485],
        [0.6344, 0.5009, 0.1902, 0.1536]])

In [19]:
image_tensor = torch.rand(size=(3,224,244))
image_tensor

tensor([[[0.5077, 0.5862, 0.6207,  ..., 0.8663, 0.2809, 0.1096],
         [0.8208, 0.3556, 0.7493,  ..., 0.9384, 0.4465, 0.8207],
         [0.0709, 0.1146, 0.2809,  ..., 0.7407, 0.0042, 0.8997],
         ...,
         [0.9015, 0.3756, 0.2737,  ..., 0.1265, 0.5278, 0.7985],
         [0.0579, 0.0284, 0.2863,  ..., 0.1998, 0.0356, 0.5303],
         [0.8322, 0.7901, 0.7199,  ..., 0.8457, 0.6135, 0.4695]],

        [[0.7218, 0.0469, 0.7985,  ..., 0.6633, 0.9145, 0.7031],
         [0.3717, 0.4013, 0.7835,  ..., 0.4274, 0.7964, 0.4942],
         [0.0532, 0.7965, 0.6265,  ..., 0.8700, 0.3706, 0.2814],
         ...,
         [0.7494, 0.9982, 0.3522,  ..., 0.1000, 0.6955, 0.3395],
         [0.8001, 0.4784, 0.5694,  ..., 0.8049, 0.5255, 0.7027],
         [0.6619, 0.9930, 0.5540,  ..., 0.8146, 0.8465, 0.0500]],

        [[0.2168, 0.2144, 0.0697,  ..., 0.2297, 0.1938, 0.8590],
         [0.0468, 0.0089, 0.4067,  ..., 0.2758, 0.3074, 0.0923],
         [0.3565, 0.3115, 0.7506,  ..., 0.1994, 0.8147, 0.

In [20]:
#ZEROS
ZEROS = torch.zeros([2,2,2])
ZEROS

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

RANGE

In [21]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#creating tensors like
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 Tensor datatypes

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### 3 COMMON ERRORs
    1 Tensors not right datatype
    2 Tensors not right shape
    3 Tensors not on right devise

In [25]:
#Information from tensors
some_tensor = torch.rand(3,4)

In [26]:
print (f'Datatype: {some_tensor.dtype}')
print (f'Size: {some_tensor.size()}')
print (f'Device: {some_tensor.device}')

Datatype: torch.float32
Size: torch.Size([3, 4])
Device: cpu


### Tensor manipulations

In [27]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [28]:
tensor * 10

tensor([10, 20, 30])

In [29]:
tensor / 10

tensor([0, 0, 0])

### Matrix multiplication

In [30]:
torch.matmul(tensor,tensor)

tensor(14)

In [31]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 2] at C:\w\1\s\tmp_conda_3.7_183424\conda\conda-bld\pytorch_1570818936694\work\aten\src\TH/generic/THTensorMath.cpp:197

In [34]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


### Transpose

In [39]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [38]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [40]:
tensor_C = torch.tensor([[1, 2, 3],
                         [4, 5, 6], 
                         [7, 8, 9]], dtype=torch.float32)

In [41]:
tensor_C.T

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

### Tensor propperties aggregation

In [58]:
# Returns position of max value in tensor
tensor_C.argmax(dim=1)

tensor([2, 2, 2])

In [57]:
tensor_C.shape

torch.Size([3, 3])

In [79]:
tensor_D = torch.tensor([[12, 2, 1],
                         [4, 13, 6]
                         ], dtype=torch.float32)

In [84]:
tensor_D.argmin(), tensor_D.min(1)

(tensor(2),
 torch.return_types.min(
 values=tensor([1., 4.]),
 indices=tensor([2, 0])))

### Reshaping stacking squeesing and unsqueezing tensors
    Reshaping - reshapes an input tensor to a defined shape
    View - Return a view of an input tensor of a certian shape but keep the same memory object as original
    Stacking  - combine multiple tensors on top of each other(vstack o hstack)
    Squeeze - removes all '1' dimensions from a tensor
    Unsqeueze - add a '1' dimension to a target tensor
    Permute - return a view of the input dimensions permuted (swapped) in a certain way

In [101]:
import torch
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [108]:
#Add an extra formation
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [109]:
# change view | chenging z cnghes x (same memory on both)
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [110]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
x_stacked = torch.stack([x, x, x, x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [113]:
#Squeeze and unsqueeze - removes all single dimensions from target tensor
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [116]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [117]:
# Orginal haven't changed
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
# torch unsqueeze adds single dimension
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [135]:
x_reshaped.unsqueeze(dim=1), x_reshaped.unsqueeze(dim=1).shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [137]:
x_reshaped.unsqueeze(dim=2), x_reshaped.unsqueeze(dim=2).shape

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [141]:
# Permute - rearrenges dimnesions in specified order
x_original = torch.rand(size=(2,2,1))
x_permuted = x_original.permute(2,0,1)

In [145]:
x_permuted ,x_original

(tensor([[[0.0894, 0.5994],
          [0.9123, 0.7468]]]),
 tensor([[[0.0894],
          [0.5994]],
 
         [[0.9123],
          [0.7468]]]))

In [149]:
x_permuted[0][0][0] = 0

In [150]:
x_permuted

tensor([[[0.0000, 0.5994],
         [0.9123, 0.7468]]])

In [151]:
x_original

tensor([[[0.0000],
         [0.5994]],

        [[0.9123],
         [0.7468]]])

In [153]:
#!!! view only changes the view of original, doesn't make copy of it in 
# memory it links to roginal(shares same memory with original.
#Changes in view data changes the orgignal data


In [155]:
x_permuted[0][0][1] 

tensor(0.5994)

In [156]:
x_permuted[0, 0, 1] 

tensor(0.5994)

### Indexing

In [158]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [159]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [162]:
x[0,0]

tensor([1, 2, 3])

In [163]:
x[0,0,0]

tensor(1)

In [175]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
3:33