In [1]:
import torch
torch.__version__

'1.3.0'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [15]:
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([3])

In [18]:
#Dimension is number of square brackets

In [22]:
# MATRIX
MATRIX = torch.tensor([[7,8,8],
                       [9,10,9]])
MATRIX

tensor([[ 7,  8,  8],
        [ 9, 10,  9]])

In [23]:
MATRIX.ndim

2

In [24]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
ONES = torch.ones([2,2,2])

In [26]:
ONES

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])