In [4]:
import torch
torch.__version__

'2.1.0.dev20230707'

In [5]:

import math
# this ensures that the current MacOS version is at least 12.3+
print(torch.backends.mps.is_available())
# this ensures that the current current PyTorch installation was built with MPS activated.
print(torch.backends.mps.is_built())

True
True


In [6]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([3])

In [11]:
#Dimension is number of square brackets

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8,8],
                       [9,10,9]])
MATRIX

tensor([[ 7,  8,  8],
        [ 9, 10,  9]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 3])

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
ONES = torch.ones([2,2,2])

In [18]:
ONES

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [19]:
ONES = torch.ones([2,2,2,2])

In [20]:
ONES

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [21]:
# RAND tensors
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.5336, 0.8060, 0.0935, 0.1015],
        [0.5072, 0.9178, 0.2064, 0.6351],
        [0.0943, 0.5522, 0.0496, 0.7900]])

In [22]:
image_tensor = torch.rand(size=(3,224,244))
image_tensor

tensor([[[0.1761, 0.4034, 0.0415,  ..., 0.8269, 0.9981, 0.3644],
         [0.3237, 0.7129, 0.8433,  ..., 0.1010, 0.7586, 0.0880],
         [0.6849, 0.2623, 0.1111,  ..., 0.4565, 0.1782, 0.5356],
         ...,
         [0.6947, 0.3679, 0.6341,  ..., 0.5482, 0.9264, 0.6405],
         [0.1379, 0.6213, 0.4932,  ..., 0.1881, 0.2577, 0.5901],
         [0.9873, 0.1209, 0.1584,  ..., 0.6513, 0.3275, 0.9071]],

        [[0.5105, 0.6772, 0.2294,  ..., 0.7170, 0.3829, 0.0029],
         [0.6210, 0.9707, 0.2016,  ..., 0.5977, 0.6518, 0.7890],
         [0.7305, 0.4664, 0.8645,  ..., 0.0823, 0.4367, 0.4480],
         ...,
         [0.2670, 0.0945, 0.8724,  ..., 0.2304, 0.4658, 0.1616],
         [0.2001, 0.1342, 0.6999,  ..., 0.6232, 0.1069, 0.6638],
         [0.0412, 0.0328, 0.5565,  ..., 0.6135, 0.0043, 0.6026]],

        [[0.9351, 0.0847, 0.0909,  ..., 0.2789, 0.0492, 0.9501],
         [0.5952, 0.2287, 0.4163,  ..., 0.0836, 0.9919, 0.3117],
         [0.5599, 0.3638, 0.5232,  ..., 0.3248, 0.7594, 0.

In [23]:
#ZEROS
ZEROS = torch.zeros([2,2,2])
ZEROS

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

RANGE

In [24]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#creating tensors like
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 Tensor datatypes

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### 3 COMMON ERRORs
    1 Tensors not right datatype
    2 Tensors not right shape
    3 Tensors not on right devise

In [28]:
#Information from tensors
some_tensor = torch.rand(3,4)

In [29]:
print (f'Datatype: {some_tensor.dtype}')
print (f'Size: {some_tensor.size()}')
print (f'Device: {some_tensor.device}')

Datatype: torch.float32
Size: torch.Size([3, 4])
Device: cpu


### Tensor manipulations

In [30]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

In [33]:
torch.matmul(tensor,tensor)

tensor(14)

In [34]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [35]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


### Transpose

In [36]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [37]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [38]:
tensor_C = torch.tensor([[1, 2, 3],
                         [4, 5, 6], 
                         [7, 8, 9]], dtype=torch.float32)

In [39]:
tensor_C.T

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

### Tensor propperties aggregation

In [40]:
# Returns position of max value in tensor
tensor_C.argmax(dim=1)

tensor([2, 2, 2])

In [41]:
tensor_C.shape

torch.Size([3, 3])

In [42]:
tensor_D = torch.tensor([[12, 2, 1],
                         [4, 13, 6]
                         ], dtype=torch.float32)

In [43]:
tensor_D.argmin(), tensor_D.min(1)

(tensor(2),
 torch.return_types.min(
 values=tensor([1., 4.]),
 indices=tensor([2, 0])))

### Reshaping stacking squeesing and unsqueezing tensors
    Reshaping - reshapes an input tensor to a defined shape
    View - Return a view of an input tensor of a certian shape but keep the same memory object as original
    Stacking  - combine multiple tensors on top of each other(vstack o hstack)
    Squeeze - removes all '1' dimensions from a tensor
    Unsqeueze - add a '1' dimension to a target tensor
    Permute - return a view of the input dimensions permuted (swapped) in a certain way

In [44]:
import torch
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
#Add an extra formation
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
# change view | chenging z cnghes x (same memory on both)
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [48]:
x_stacked = torch.stack([x, x, x, x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [49]:
#Squeeze and unsqueeze - removes all single dimensions from target tensor
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Orginal haven't changed
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
# torch unsqueeze adds single dimension
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [53]:
x_reshaped.unsqueeze(dim=1), x_reshaped.unsqueeze(dim=1).shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [54]:
x_reshaped.unsqueeze(dim=2), x_reshaped.unsqueeze(dim=2).shape

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [55]:
# Permute - rearrenges dimnesions in specified order
x_original = torch.rand(size=(2,2,1))
x_permuted = x_original.permute(2,0,1)

In [56]:
x_permuted ,x_original

(tensor([[[0.1693, 0.8906],
          [0.3794, 0.6790]]]),
 tensor([[[0.1693],
          [0.8906]],
 
         [[0.3794],
          [0.6790]]]))

In [57]:
x_permuted[0][0][0] = 0

In [58]:
x_permuted

tensor([[[0.0000, 0.8906],
         [0.3794, 0.6790]]])

In [59]:
x_original

tensor([[[0.0000],
         [0.8906]],

        [[0.3794],
         [0.6790]]])

In [60]:
#!!! view only changes the view of original, doesn't make copy of it in 
# memory it links to roginal(shares same memory with original.
#Changes in view data changes the orgignal data


In [61]:
x_permuted[0][0][1] 

tensor(0.8906)

In [62]:
x_permuted[0, 0, 1] 

tensor(0.8906)

### Indexing

In [63]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
x[0,0]

tensor([1, 2, 3])

In [66]:
x[0,0,0]

tensor(1)

In [67]:
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch and numpy

In [70]:
#Data in Numpy, want in Torch tensor
#torch.from_numpy(ndarray)
# torch tensor to Numpy torch.tensor.numpy()

In [73]:
#Numpy -> tensot
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
#Numpy default dtype float64, when pytorch float32

In [75]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducebility

In [87]:
random_tensor_A = torch.rand(3, 3)
random_tensor_B = torch.rand(3, 3)
print (random_tensor_A)
print (random_tensor_B)
print (random_tensor_A == random_tensor_B)

tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])
tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [18]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [2]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)
print (random_tensor_C)
print (random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [3]:
#Rand seed работает в методах той ячейки в которой он 
#прописан  Его надо каждый раз повторять

In [4]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)
print (random_tensor_C)
print (random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [5]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 3)
random_tensor_D = torch.rand(3, 3)
print (random_tensor_C)
print (random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


### GPU SUPPORT

In [6]:
#Getting a gpu

In [7]:
#Check GPU access
import torch
torch.cuda.is_available()

False

In [123]:
# Check that MPS is available
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        print("MPS not available because the current PyTorch install was not "
              "built with MPS enabled.")
    else:
        print("MPS not available because the current MacOS version is not 12.3+ "
              "and/or you do not have an MPS-enabled device on this machine.")

else:
    mps_device = torch.device("mps")

    # Create a Tensor directly on the mps device
    x = torch.ones(5, device=mps_device)
    # Or
    x = torch.ones(5, device="mps")

    # Any operation happens on the GPU
    y = x * 2
    
    print (y)

    # Move your model to mps just like any other device
#    model = YourFavoriteNet()
#    model.to(mps_device)

    # Now every call runs on the GPU
#    pred = model(x)

tensor([2., 2., 2., 2., 2.], device='mps:0')


In [8]:
#Setup device agnostic code
device = 'mps'

In [9]:
# Putting tensors and model on gpu
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print (tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_on_GPU = tensor.to(device)

#Tensor not on GPU
print (tensor_on_GPU, tensor_on_GPU.device)

tensor([1, 2, 3], device='mps:0') mps:0


In [133]:
###
#Good manner to use such code
# Set device type
#device = "cuda" if torch.cuda.is_available() else "cpu"
#device


In [134]:
#Tensor back to cpu
tensor_on_cpu = tensor_on_GPU.cpu()

In [11]:
import time

In [21]:
# Calculation time
start = time.time()
torch.manual_seed(RANDOM_SEED)
my_test_tensor_cpu = torch.rand((5056, 5056),device='cpu')
for i in range(500):
    my_test_tensor_cpu = my_test_tensor_cpu*5000
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
    torch.matmul(my_test_tensor_cpu, my_test_tensor_cpu)
finish = time.time()
elapsed =finish-start
print (f'time needed to calculation:{elapsed}')

time needed to calculation:1411.2659499645233


In [22]:
# Calculation time
start = time.time()
torch.manual_seed(RANDOM_SEED)
my_test_tensor_gpu = torch.rand((5056, 5056),device = 'mps')
for i in range(500):
    my_test_tensor_gpu = my_test_tensor_gpu*5000
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
    torch.matmul(my_test_tensor_gpu, my_test_tensor_gpu)
finish = time.time()
elapsed =finish-start
print (f'time needed to calculation:{elapsed}')

time needed to calculation:840.8752999305725


In [ ]:
04.17